// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwuqPdCtiGuIPduJzXjLccvROqCpQfacU',
    appId: '1:682836137366:web:14af6aae29207dccabf9b7',
    messagingSenderId: '682836137366',
    projectId: 'vitatrack-2026',
    authDomain: 'vitatrack-2026.firebaseapp.com',
    storageBucket: 'vitatrack-2026.firebasestorage.app',
    measurementId: 'G-G7220GRHB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZOcLYVXzp3Tix_jXqXWTATjBoxEYy9CM',
    appId: '1:682836137366:android:6a1f1c92784f9151abf9b7',
    messagingSenderId: '682836137366',
    projectId: 'vitatrack-2026',
    storageBucket: 'vitatrack-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD05Q5MCgW3BDeUGZdvsVP-DeqPChNpZYg',
    appId: '1:682836137366:ios:a0c0bba964e8d2daabf9b7',
    messagingSenderId: '682836137366',
    projectId: 'vitatrack-2026',
    storageBucket: 'vitatrack-2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterVitatrack1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD05Q5MCgW3BDeUGZdvsVP-DeqPChNpZYg',
    appId: '1:682836137366:ios:a0c0bba964e8d2daabf9b7',
    messagingSenderId: '682836137366',
    projectId: 'vitatrack-2026',
    storageBucket: 'vitatrack-2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterVitatrack1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwuqPdCtiGuIPduJzXjLccvROqCpQfacU',
    appId: '1:682836137366:web:aa57f1e00db39805abf9b7',
    messagingSenderId: '682836137366',
    projectId: 'vitatrack-2026',
    authDomain: 'vitatrack-2026.firebaseapp.com',
    storageBucket: 'vitatrack-2026.firebasestorage.app',
    measurementId: 'G-KJ1XJW0NWZ',
  );
}
